<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AlgorithmAnalysis.Contracts\AlgorithmAnalysis.Contracts.csproj" />
    <ProjectReference Include="..\AlgorithmCatalog.Domain\AlgorithmCatalog.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
